### ISSUE TITLE
Is the resolution we show now for CCU or PC?  I assume CCU -- would it be good to add PC?

### ISSUE THREAD

**Issue by Radisovik** [nilicule/StadiaGameDB#11]

**Comment by Skylled** [comment]
Chromecast Ultra is currently the only to get 4K resolution on Stadia, even if you have a 4K monitor on your PC. Adding PC would essentially be adding "1080p60" to every game.

**Comment by Mafrans** [comment]
> Chromecast Ultra is currently the only way to get 4K resolution on Stadia, even if you have a 4K monitor on your PC. Adding PC would essentially be adding "1080p60" to every game.

This is no longer the case
