### ISSUE TITLE
CORB (Cross Origin Read Blocking) blocks get requests.

### ISSUE THREAD

**Issue by Mafrans** [nilicule/StadiaGameDB#26]
CORB currently blocks access to requesting data directly from the website. This is bad for the numerous services (like [Stadia+](https://github.com/Mafrans/StadiaPlus)) that rely on StadiaGameDB for some of their core features. These services currently grab data directly from https://raw.githubusercontent.com/nilicule/StadiaGameDB/master/data/gamedb.json as it does not block access, but this causes issues for users as they cannot know directly what the data is being used for (in chrome, it is only shown as 'https://raw.githubusercontent.com/*').

**Comment by nilicule** [comment]
EnableD CORS on the server, with support for preflight requests - let me know if you run into any problems
