### ISSUE TITLE
Include UUIDs in the database

### ISSUE THREAD

**Issue by Mafrans** [nilicule/StadiaGameDB#27]
Including UUIDs of games in the database will allow services using this website as an API to match the UUID of a game and get information directly from it. Currently, the UUID can be harvested from the image tag, which is a bad and inefficient solution to a simple problem.

**Comment by Mafrans** [comment]
The UUID can be found in the store page, 

For a game with the store url https://stadia.google.com/store/details/632522c846a041ce801e47b96ba2e265rcp1/sku/17affc92b9ca47a7b64e748609ed25af the UUID would be "632522c846a041ce801e47b96ba2e265rcp1"

**Comment by nilicule** [comment]
Yup, good idea - I'll add this later tonight
