### ISSUE TITLE
Final Fantasy XV 4K60

### ISSUE THREAD

**Issue by ArkhLink** [nilicule/StadiaGameDB#31]
Hi,
I didn't find a way to contact admin(s), so I came here.

Is it possible to update Final Fantasy XV information ? This game can be played with a 4K resolution at 60fps.

For information, I have a 2K monitor, but I forced the 4K with "Stadia+" chrome extension.

![final_fantasy_xv_4k](https://user-images.githubusercontent.com/11856129/79116560-1be1dd00-7d89-11ea-941d-c32d4902ac02.png)

**Comment by chocomega** [comment]
The video stream may be at 4K 60 fps but it does not mean the game is also rendering natively at this resolution and frame rate. It could be upscaled so that information is not relevant.
Thanks for your input anyway.

**Comment by ArkhLink** [comment]
Thank you for your answer.
