### ISSUE TITLE
Family Feud

### ISSUE THREAD

**Issue by chocomega** [nilicule/StadiaGameDB#71]
https://stadia.google.com/store/details/5ba98de70c8c4b64bf56ca9009d60e62rcp1/sku/3af579475c334c62985ac80b3dfed0bap

**Comment by nilicule** [comment]
I'm actually unable to see this one unless I use your direct link

Any chance you can grab the following things for me:
- release date (lists as empty for me)
- the small image in the games list page

**Comment by chocomega** [comment]
Sure!

Release date
November 12, 2020

https://lh3.googleusercontent.com/LGzSucujCWToUIJGjiU6xDYy5S1T7CXMkj-V3SEwcdlIBnIvx1fJ7tNWWkhaLsG-0DnZA63jAAcT5RJWyttgTu-0QuWtGmqs51fPhTlbnMW2CgwnGxAMu-vsZNA=s1920-rw

**Comment by nilicule** [comment]
Awesome, thanks!
